//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCCIntegration {
	
	
	public partial class SearchCCCIntegration {
		
		protected System.Web.UI.WebControls.Content BodyContent;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl errorPlaceholder;
		
		protected System.Web.UI.WebControls.RadioButtonList termType;
		
		protected System.Web.UI.WebControls.TextBox term;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator termValidator;
		
		protected System.Web.UI.WebControls.Label pubYearLbl;
		
		protected System.Web.UI.WebControls.TextBox pubYear;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator yearValidator;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator yearValueValidator;
		
		protected System.Web.UI.WebControls.Button btnSearch;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl noResultsFound;
		
		protected System.Web.UI.WebControls.GridView resultsGrid;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ulPagger;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl liFirst;
		
		protected System.Web.UI.WebControls.LinkButton lnkFirst;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl liPrev;
		
		protected System.Web.UI.WebControls.LinkButton lnkPrev;
		
		protected System.Web.UI.WebControls.Repeater rptPages;
		
		protected System.Web.UI.WebControls.LinkButton lnkPageNumber;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl liNext;
		
		protected System.Web.UI.WebControls.LinkButton lnkNext;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl liLast;
		
		protected System.Web.UI.WebControls.LinkButton lnkLast;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl estFields;
	}
}
